spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 12345678
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: chatapp90104@gmail.com
    password: yhznvdpzzmqpcpje
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false

server:
  error:
    include-message: always